name: Betterssentials
main: me.snowman.betterssentials.Betterssentials
version: 2.0.0
author: SnowmanFTW
depend:
  - Vault

commands:
  afk:
    description: Sets your afk status
    usage: /<command> [player]
  balance:
    description: Shows your in-game balance
    usage: /<command> [player]
    aliases:
      - bal
      - money
  ban:
    description: Ban someone from the server
    usage: /<command> <player> [reason]
  broadcast:
    description: Broadcast a message to the whole server
    usage: /<command> <message>
    aliases:
      - bc
  clearchat:
    description: Clears the server chat
    usage: /<command> [lines]
    aliases:
      - cc
  clearinventory:
    description: Clears your inventory
    usage: /<command> [player]
    aliases:
      - clear
      - clearinv
      - ci
  economy:
    description: Manage the economy of a player
    usage: /<command> <player> <set/add/remove> <amount>
    aliases:
      - eco
  experience:
    description: Manage the xp of a plyer
    usage: /<command> <player> <set/add> <amount>
    aliases:
      - xp
      - exp
  fly:
    description: Allow flying for a plyer
    usage: /<command> [player]
  unban:
    description: Unban someone from the server
    usage: /<command> <player>
permissions:
  betterssentials.afk:
    description: Permisssion of afk command
  betterssneitlas.balance:
    description: Permission of balance command
  betterssentials.ban:
    description: Permission of ban command
  betterssentials.broadcast:
    description: Permission of broadcast command
  betterssentials.clearchat:
    description: Permission of clearchat comand
  betterssentials.economy:
    description: Permission of economy command
  betterssentials.experience:
    description: Permission of experience command
  betterssentials.fly:
    description: Permission of fly command
  betterssentials.unban:
    description: Permission of unban command