name: Betterssentials
main: me.snowman.betterssentials.Betterssentials
version: 2.0.0
author: SnowmanFTW
depend:
  - Vault

commands:
  afk:
    description: Sets your afk status
    usage: /<command> [player]
  balance:
    description: Shows your in-game balance
    usage: /<command> [player]
    aliases:
      - bal
      - money
  ban:
    description: Ban someone from the server
    usage: /<command> <player> [reason]
  broadcast:
    description: Broadcast a message to the whole server
    usage: /<command> <message>
    aliases:
      - bc
  clearchat:
    description: Clears the server chat
    usage: /<command> [lines]
    aliases:
      - cc
  clearinventory:
    description: Clears your inventory
    usage: /<command> [player]
    aliases:
      - clear
      - clearinv
      - ci
  economy:
    description: Manage the economy of a player
    usage: /<command> <player> <set/add/remove> <amount>
    aliases:
      - eco
  experience:
    description: Manage the xp of a player
    usage: /<command> <player> <set/add> <amount>
    aliases:
      - xp
      - exp
  feed:
    description: Set the food level to max of a player
    usage: /<command> [player]
  fly:
    description: Allow flying for a player
    usage: /<command> [player]
  gamemode:
    description: Switch gamemode of a player
    usage: /<command> <0/1/2/3/survival/creative/adventure/spectator/s/c/a/spec> [player]
    aliases:
      - gm
  give:
    description: Give an item to someone
    usage: /<command> <player> <material> [amount]
  god:
    description: Make someone invulnerable
    usage: /<command> [player]
  hat:
    description: Put on a new hat on you
    usage: /<command>
  heal:
    description: Set the health level to the max
    usage: /<command> [player]
  kick:
    description: Kick a player from the server
    usage: /<command> [player]
  kill:
    description: Kill a player on the server
    usage: /<command> <player>
  list:
    description: List all players on the server
    usage: /<command>
  me:
    description: Displays a cool message
    usage: /<command> <message>
  unban:
    description: Unban someone from the server
    usage: /<command> <player>
permissions:
  betterssentials.afk:
    description: Permisssion of afk command
  betterssneitlas.balance:
    description: Permission of balance command
  betterssentials.ban:
    description: Permission of ban command
  betterssentials.broadcast:
    description: Permission of broadcast command
  betterssentials.clearchat:
    description: Permission of clearchat comand
  betterssentials.economy:
    description: Permission of economy command
  betterssentials.experience:
    description: Permission of experience command
  betterssentials.feed:
    description: Permission of feed command
  betterssentials.fly:
    description: Permission of fly command
  betterssentials.gamemode:
    description: Permission of gamemode command
  betterssentials.give:
    description: Permission of give command
  betterssentials.god:
    description: Permission of god command
  betterssentials.hat:
    description: Permission of hat command
  betterssentials.heal:
    description: Permission of heal command
  betterssentials.kick:
    description: Permission of kick command
  betterssentials.kill:
    description: Permission of kill command
  betterssentials.list:
    description: Permission of list command
  betterssentials.me:
    description: Permission of me command
  betterssentials.unban:
    description: Permission of unban command