name: Betterssentials
main: me.snowman.betterssentials.Betterssentials
version: 2.0.0
author: SnowmanFTW

commands:
  afk:
    description: Sets your afk status
    usage: /<command> [player]
  balance:
    description: Shows your in game balance
    usage: /<command> [player]
permissions:
  betterssentials.afk:
    description: Permisssion of afk command
  betterssneitlas.balance:
    description: Permission of balance command